/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '7/20/20, 2:14 AM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-754.6.3.el6.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/38/main?locale=en_US&zone=GMT%252B02%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F38%2F=' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=COVID.MCMC_WEEKLY_POST out=WORK.TempSorted2236;
	by country region_code region_name;
run;

proc means data=WORK.TempSorted2236 chartype mean std min max median n 
		vardef=df qmethod=os;
	var mortality i0 R0_0 R0_1 beta gamma;
	output out=work.post_weekly_stat mean=std=min=max=median=n= / autoname;
	by country region_code region_name;
run;

proc datasets library=WORK noprint;
	delete TempSorted2236;
	run;